"""goals feature added, transaction model now has destiation ids for account and goal, account and transaction foreign keys specified to prevent tables using wrong id

Revision ID: 4db1163fbbf7
Revises: 07bb42c68c8b
Create Date: 2026-04-09 22:35:30.706812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4db1163fbbf7'
down_revision: Union[str, Sequence[str], None] = '07bb42c68c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('destination_account_id', sa.Integer(), nullable=True))
    op.add_column('transaction', sa.Column('destination_goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'account', ['destination_account_id'], ['id'])
    op.create_foreign_key(None, 'transaction', 'account', ['destination_goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'destination_goal_id')
    op.drop_column('transaction', 'destination_account_id')
    # ### end Alembic commands ###
