"""add ondelete behavior to foreign keys

Revision ID: 57d8342e01fe
Revises: 7601392d7ac4
Create Date: 2026-04-25 21:52:50.132383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d8342e01fe'
down_revision: Union[str, Sequence[str], None] = '7601392d7ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('account_user_id_fkey'), 'account', type_='foreignkey')
    op.create_foreign_key(None, 'account', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('budget_user_id_fkey'), 'budget', type_='foreignkey')
    op.create_foreign_key(None, 'budget', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('category_user_id_fkey'), 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('goal_user_id_fkey'), 'goal', type_='foreignkey')
    op.create_foreign_key(None, 'goal', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('transaction_account_id_fkey'), 'transaction', type_='foreignkey')
    op.drop_constraint(op.f('transaction_destination_goal_id_fkey'), 'transaction', type_='foreignkey')
    op.drop_constraint(op.f('transaction_source_goal_id_fkey'), 'transaction', type_='foreignkey')
    op.drop_constraint(op.f('transaction_destination_account_id_fkey'), 'transaction', type_='foreignkey')
    op.drop_constraint(op.f('transaction_user_id_fkey'), 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transaction', 'goal', ['destination_goal_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transaction', 'account', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transaction', 'goal', ['source_goal_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transaction', 'account', ['destination_account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_user_id_fkey'), 'transaction', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('transaction_destination_account_id_fkey'), 'transaction', 'account', ['destination_account_id'], ['id'])
    op.create_foreign_key(op.f('transaction_source_goal_id_fkey'), 'transaction', 'goal', ['source_goal_id'], ['id'])
    op.create_foreign_key(op.f('transaction_destination_goal_id_fkey'), 'transaction', 'goal', ['destination_goal_id'], ['id'])
    op.create_foreign_key(op.f('transaction_account_id_fkey'), 'transaction', 'account', ['account_id'], ['id'])
    op.drop_constraint(None, 'goal', type_='foreignkey')
    op.create_foreign_key(op.f('goal_user_id_fkey'), 'goal', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key(op.f('category_user_id_fkey'), 'category', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'budget', type_='foreignkey')
    op.create_foreign_key(op.f('budget_user_id_fkey'), 'budget', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.create_foreign_key(op.f('account_user_id_fkey'), 'account', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
