"""add source_goal_id to transaction

Revision ID: 7601392d7ac4
Revises: f8b64a291830
Create Date: 2026-04-20 20:37:23.049947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7601392d7ac4'
down_revision: Union[str, Sequence[str], None] = 'f8b64a291830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('source_goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'goal', ['source_goal_id'], ['id'])
    # ### end Alembic commands ###

    op.execute("""
    UPDATE "transaction"
    SET source_goal_id = destination_goal_id,
        destination_goal_id = NULL
    WHERE description LIKE 'Withdrawal from%'
""")
    


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("""
    UPDATE "transaction"
    SET destination_goal_id = source_goal_id,
        source_goal_id = NULL
    WHERE source_goal_id IS NOT NULL
""")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'source_goal_id')
    # ### end Alembic commands ###