"""goal id foreign key change

Revision ID: f8b64a291830
Revises: 4db1163fbbf7
Create Date: 2026-04-11 19:10:41.737963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8b64a291830'
down_revision: Union[str, Sequence[str], None] = '4db1163fbbf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transaction_destination_goal_id_fkey'), 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'goal', ['destination_goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_destination_goal_id_fkey'), 'transaction', 'account', ['destination_goal_id'], ['id'])
    # ### end Alembic commands ###
